### PR TITLE
set up documentation CI against Julia 1.x

### PR DESCRIPTION
**Pull request by johnnychen94**
The whole documentation will be largely rewritten to:

* update to Julia 1.0
* better cooperate with current `Images.jl`
* be CI-friendly (e.g., replace Weave and `optable.jl` with `DemoCards.jl`)

It would be impossible to review if they're all squashed into one PR, so I'll set this as the common base, and make reviewable separate PRs that points to this branch.

P.S. DemoCards doesn't have the full functionality as a jump-in replacement, so I'll need to spend some of my time debugging and enhance it.

### CODE REVIEW

**Comment by johnnychen94** [comment]
Here's a preview of how https://evizero.github.io/Augmentor.jl/operations/ will be changed to. Which one do you guys prefer?

# List theme
list

# Grid theme
grid


Each card has a link to its reference/explaination page, which basically looks like this:

image

**Comment by Evizero** [comment]
Grid seems to be a little bit more readable. Any chance you can fix the black background?

**Comment by Evizero** [comment]
btw. I don't recall to what extend I transferred stuff here, but I do have some doc stuff for augmentor at juliaml: https://github.com/JuliaML/FileStorage/tree/master/Augmentor
In case you wondered how I created some pieces.

I know... I wasn't exactly spending much time on cleaning up my documentation "framework"

**Comment by johnnychen94** [comment]
> Any chance you can fix the black background?

Yeah, I just tried to make a fresh build of those scripts from scratch with my own stuff. But it's doable --https://github.com/Evizero/Augmentor.jl/blob/master/docs/optable.jl gives a nice example of this already.

There're more details that need to be fixed. This is just a preview of my experiments on the layouts.

> I know... I wasn't exactly spending much time on cleaning up my documentation "framework"

😄 that (documentation) was more than elaborative to me

**Comment by johnnychen94** [comment]
This is mostly done now.

As a brief summary:

* [operations gallery](https://evizero.github.io/Augmentor.jl/operations/) and [tutorials](https://evizero.github.io/Augmentor.jl/generated/mnist_elastic/) are now generated by [DemoCards.jl](https://github.com/johnnychen94/DemoCards.jl). `optable.jl` is rewrite with the new `mosaicview` and `exampleweave.jl` is replaced by `DemoCards.jl` + `Literate.jl`.
* deprecation and jldoctest references fixes (jldoctest only passes in Julia 1.6-dev)
* `Knet.jl` example is removed now, I'll add an example for Flux.jl in future PRs. (#67)

A lot of changes are involved here and it's pretty hard to review them line by line. I would suggest build it locally and view the generated pages.

The `ISICArchive.jl` package is not registered in General, so I have to hack it a bit in `make.jl` as a temporary solution (if I don't want to check in `Manifest.toml`). We should either register this package or replace it with probably `TestImages` or `MLDatasets`. I'll leave this to future work. (CRef. https://github.com/Evizero/ISICArchive.jl/issues/3)

@Evizero do you want to take a look at this?

**Comment by Evizero** [comment]
I don't have a local julia installation currently. any chance you can show some screenshots of the major things?

**Comment by johnnychen94** [comment]
The biggest changes are on [operations](https://evizero.github.io/Augmentor.jl/operations/). The tutorials are built with DemoCards with a List theme.

`Plots`, `Reel` are not used in this PR; instead, I use `ImageMagick` to generate gifs.

---

# Operations




image


---

# Tutorials

Integrate with Flux.jl is not included in this PR:

**Comment by Evizero** [comment]
Looking good. Thank you for all that hard work. Feel free to merge when you are ready

**Comment by johnnychen94** [comment]
Let me merge this and see if it gets successfully deployed to `gh-pages` branch

**Comment by johnnychen94** [comment]
deployed in https://evizero.github.io/Augmentor.jl/dev/

**Comment by Evizero** [comment]
amazing!

**Pull request merged**
